/**
 * v3 全局边界常量（与策划 types.ts 对齐）
 */

export const GAME_CONSTANTS = {
  CD_MIN: 0.3,
  CD_BREAK_MIN: 0.1,
  SHIELD_MAX_RATIO: 2.5,
  SELL_RATIO: 0.7,
  DOT_STACK_MAX: 10,
  DOT_TICK_INTERVAL: 1.0,
  DOT_DECAY_PER_TICK: 1,
  SLOT_COUNT: 6,
  OVERLOAD_CD_FORCED: 0.5,
  BARREL_SCALING_PER_ITEM: 0.1,
  SINGLE_FRAME_TRIGGER_MAX: 1,
  ADRENALINE_SELF_DAMAGE_MIN_HP: 1,
} as const;

/** @deprecated 请使用 GAME_CONSTANTS.CD_MIN */
export const CD_MIN = GAME_CONSTANTS.CD_MIN;

/** @deprecated 请使用 GAME_CONSTANTS.SHIELD_MAX_RATIO */
export const SHIELD_MAX_RATIO = GAME_CONSTANTS.SHIELD_MAX_RATIO;
